/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClientSeiteNeu;
 
/**
 *
 * @author alisi
 */
public class ChartMenu extends javax.swing.JFrame {

    /**  
     * Creates new form ChartMenu
     */
    public ChartMenu() {
 



        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelZ1In = new javax.swing.JLabel();
        jLabelZ1Out = new javax.swing.JLabel();
        jLabelManuel1 = new javax.swing.JLabel();
        jLabelManuel3 = new javax.swing.JLabel();
        jLabelZ2In = new javax.swing.JLabel();
        jLabelZ2Out = new javax.swing.JLabel();
        jLabelManuel2 = new javax.swing.JLabel();
        jLabelManuel4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelTempSoll = new javax.swing.JLabel();
        jLabelTempTol = new javax.swing.JLabel();
        jLabelDampTol = new javax.swing.JLabel();
        jLabelDampSoll = new javax.swing.JLabel();
        jLabelCo2Tol = new javax.swing.JLabel();
        jLabelCo2Soll = new javax.swing.JLabel();
        jLabelEthylTol = new javax.swing.JLabel();
        jLabelEthylSoll = new javax.swing.JLabel();
        jLabelMultiTemp = new javax.swing.JLabel();
        jLabelMultiCo2 = new javax.swing.JLabel();
        jLabelMultiDamp = new javax.swing.JLabel();
        jLabelMultiEthyl = new javax.swing.JLabel();
        statusAnzeigeRoom = new javax.swing.JTextField();
        stopButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        jTextFieldAnzeige = new javax.swing.JTextField();
        timeAnzeigeHauptMenu = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaClientSeite = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabelSetTimeCircLeft = new javax.swing.JLabel();
        jLabelIstTimeCircLeft = new javax.swing.JLabel();
        jButtonCircLeft = new javax.swing.JButton();
        jLabelSetTimeCircRight = new javax.swing.JLabel();
        jLabelIstTimeRight = new javax.swing.JLabel();
        jButtonCircRight = new javax.swing.JButton();
        jLabelSetTimeSuction = new javax.swing.JLabel();
        jButtonSuction = new javax.swing.JButton();
        jLabelIstTimeSuction = new javax.swing.JLabel();
        jLabelSetTimeFreshAir = new javax.swing.JLabel();
        jLabelIstTimeFreshAir = new javax.swing.JLabel();
        jButtonFreshAir = new javax.swing.JButton();
        jLabelIstTimeEthylen = new javax.swing.JLabel();
        jButtonEthylen = new javax.swing.JButton();
        jLabelSetTimeEthylen = new javax.swing.JLabel();
        jButtonDamper = new javax.swing.JButton();
        jLabelSetTimeDamper = new javax.swing.JLabel();
        jLabelIstTimeDamper = new javax.swing.JLabel();
        jLabelSetTimeHeater = new javax.swing.JLabel();
        jLabelIstTimeHeater = new javax.swing.JLabel();
        jButtonHeater = new javax.swing.JButton();
        jLabelIstTimeCooler = new javax.swing.JLabel();
        jLabelSetTimeCooler = new javax.swing.JLabel();
        jButtonCooler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 678));
        setResizable(false);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setEnabled(false);
        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 380));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "[C°]"));

        jLabelZ1In.setText("jLabel10");
        jLabelZ1In.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "In1 C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(204, 0, 0))); // NOI18N
        jLabelZ1In.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelZ1Out.setText("jLabel10");
        jLabelZ1Out.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Out1 C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        jLabelZ1Out.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelManuel1.setText("jLabel10");
        jLabelManuel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "M1 C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(0, 153, 0))); // NOI18N
        jLabelManuel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelManuel3.setText("jLabel10");
        jLabelManuel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "M3 C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(0, 153, 0))); // NOI18N
        jLabelManuel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelZ2In.setText("jLabel10");
        jLabelZ2In.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "In2 C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(204, 0, 0))); // NOI18N
        jLabelZ2In.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelZ2Out.setText("jLabel10");
        jLabelZ2Out.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Out2 C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        jLabelZ2Out.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelManuel2.setText("jLabel10");
        jLabelManuel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "M2 C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(0, 153, 0))); // NOI18N
        jLabelManuel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelManuel4.setText("jLabel10");
        jLabelManuel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "M4 C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(0, 153, 0))); // NOI18N
        jLabelManuel4.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClientSeiteNeu/fan3.png"))); // NOI18N
        jLabel4.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClientSeiteNeu/fan3.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelZ1In, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabelZ2In, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelZ2Out, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelZ1Out, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelManuel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jLabelManuel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelManuel3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jLabelManuel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelZ1In)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelManuel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelManuel1)
                            .addComponent(jLabelZ1Out))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelZ2In)
                        .addComponent(jLabelZ2Out)
                        .addComponent(jLabelManuel2)
                        .addComponent(jLabelManuel4))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Room"));

        jLabelTempSoll.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelTempSoll.setText("jLabel10");

        jLabelTempTol.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelTempTol.setText("jLabel10");

        jLabelDampTol.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelDampTol.setText("jLabel10");

        jLabelDampSoll.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelDampSoll.setText("jLabel10");

        jLabelCo2Tol.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelCo2Tol.setText("jLabel10");

        jLabelCo2Soll.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelCo2Soll.setText("jLabel10");

        jLabelEthylTol.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelEthylTol.setText("jLabel10");

        jLabelEthylSoll.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelEthylSoll.setText("jLabel10");

        jLabelMultiTemp.setBackground(new java.awt.Color(204, 204, 0));
        jLabelMultiTemp.setText(" ");
        jLabelMultiTemp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Temp C°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(0, 153, 0))); // NOI18N
        jLabelMultiTemp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMultiTemp.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabelMultiTemp.setOpaque(true);

        jLabelMultiCo2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Co2 ppm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(0, 153, 0))); // NOI18N
        jLabelMultiCo2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelMultiDamp.setText(" ");
        jLabelMultiDamp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Damp %", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(0, 153, 0))); // NOI18N
        jLabelMultiDamp.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelMultiEthyl.setText(" ");
        jLabelMultiEthyl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ethyl. ppm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10), new java.awt.Color(0, 153, 0))); // NOI18N
        jLabelMultiEthyl.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMultiTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMultiDamp, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDampSoll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDampTol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMultiEthyl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTempTol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTempSoll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMultiCo2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEthylTol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEthylSoll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelCo2Soll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCo2Tol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelMultiTemp)
                                .addComponent(jLabelTempTol)
                                .addComponent(jLabelMultiCo2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCo2Tol))
                            .addComponent(jLabelTempSoll)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCo2Soll)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEthylTol)
                            .addComponent(jLabelDampSoll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEthylSoll))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelDampTol)
                                .addComponent(jLabelMultiEthyl))
                            .addComponent(jLabelMultiDamp))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusAnzeigeRoom.setBackground(new java.awt.Color(0, 255, 255));
        statusAnzeigeRoom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statusAnzeigeRoom.setText("Status"); // NOI18N
        statusAnzeigeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusAnzeigeRoomActionPerformed(evt);
            }
        });

        stopButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stopButton.setText("Stop"); // NOI18N
        stopButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        startButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startButton.setText("Start"); // NOI18N
        startButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldAnzeige.setText("jTextField1");

        timeAnzeigeHauptMenu.setBackground(new java.awt.Color(0, 255, 255));
        timeAnzeigeHauptMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        timeAnzeigeHauptMenu.setText("Datum Uhrzeit"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Clientseite"));

        jTextAreaClientSeite.setBackground(new java.awt.Color(0, 255, 255));
        jTextAreaClientSeite.setColumns(20);
        jTextAreaClientSeite.setRows(5);
        jScrollPane1.setViewportView(jTextAreaClientSeite);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSetTimeCircLeft.setText("1");
        jLabelSetTimeCircLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSetTimeCircLeft.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelIstTimeCircLeft.setText("1");
        jLabelIstTimeCircLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelIstTimeCircLeft.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jButtonCircLeft.setBackground(new java.awt.Color(255, 0, 51));
        jButtonCircLeft.setText("Circ.Left");
        jButtonCircLeft.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSetTimeCircRight.setText("1");
        jLabelSetTimeCircRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSetTimeCircRight.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelIstTimeRight.setText("1");
        jLabelIstTimeRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelIstTimeRight.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jButtonCircRight.setBackground(new java.awt.Color(255, 0, 51));
        jButtonCircRight.setText("Circ.Right");
        jButtonCircRight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSetTimeSuction.setText("1");
        jLabelSetTimeSuction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSetTimeSuction.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jButtonSuction.setBackground(new java.awt.Color(255, 0, 51));
        jButtonSuction.setText("Suction");
        jButtonSuction.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelIstTimeSuction.setText("1");
        jLabelIstTimeSuction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelIstTimeSuction.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelSetTimeFreshAir.setText("1");
        jLabelSetTimeFreshAir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSetTimeFreshAir.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelIstTimeFreshAir.setText("1");
        jLabelIstTimeFreshAir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelIstTimeFreshAir.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jButtonFreshAir.setBackground(new java.awt.Color(255, 0, 51));
        jButtonFreshAir.setText("FreshAir");
        jButtonFreshAir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelIstTimeEthylen.setText("1");
        jLabelIstTimeEthylen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelIstTimeEthylen.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jButtonEthylen.setBackground(new java.awt.Color(255, 0, 51));
        jButtonEthylen.setText("Ethylen");
        jButtonEthylen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSetTimeEthylen.setText("1");
        jLabelSetTimeEthylen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSetTimeEthylen.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jButtonDamper.setBackground(new java.awt.Color(255, 0, 51));
        jButtonDamper.setText("Damper");
        jButtonDamper.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSetTimeDamper.setText("1");
        jLabelSetTimeDamper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSetTimeDamper.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelIstTimeDamper.setText("1");
        jLabelIstTimeDamper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelIstTimeDamper.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelSetTimeHeater.setText("1");
        jLabelSetTimeHeater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSetTimeHeater.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelIstTimeHeater.setText("1");
        jLabelIstTimeHeater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelIstTimeHeater.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jButtonHeater.setBackground(new java.awt.Color(255, 0, 51));
        jButtonHeater.setText("Heater");
        jButtonHeater.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelIstTimeCooler.setText("1");
        jLabelIstTimeCooler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelIstTimeCooler.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jLabelSetTimeCooler.setText("1");
        jLabelSetTimeCooler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSetTimeCooler.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jButtonCooler.setBackground(new java.awt.Color(255, 0, 51));
        jButtonCooler.setText("Cooler");
        jButtonCooler.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCooler.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelSetTimeSuction, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabelSetTimeFreshAir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSetTimeEthylen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSetTimeDamper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSetTimeHeater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSetTimeCooler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelIstTimeSuction, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                    .addComponent(jLabelIstTimeFreshAir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelIstTimeEthylen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelIstTimeDamper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonFreshAir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSuction, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEthylen, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonDamper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelIstTimeHeater, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                    .addComponent(jLabelIstTimeCooler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonHeater, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCooler, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSetTimeCircRight, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabelSetTimeCircLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIstTimeCircLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabelIstTimeRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCircLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCircRight, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetTimeCircLeft)
                    .addComponent(jLabelIstTimeCircLeft)
                    .addComponent(jButtonCircLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetTimeCircRight)
                    .addComponent(jLabelIstTimeRight)
                    .addComponent(jButtonCircRight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetTimeSuction)
                    .addComponent(jLabelIstTimeSuction)
                    .addComponent(jButtonSuction, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetTimeFreshAir)
                    .addComponent(jLabelIstTimeFreshAir)
                    .addComponent(jButtonFreshAir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetTimeEthylen)
                    .addComponent(jLabelIstTimeEthylen)
                    .addComponent(jButtonEthylen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetTimeDamper)
                    .addComponent(jLabelIstTimeDamper)
                    .addComponent(jButtonDamper, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetTimeHeater)
                    .addComponent(jLabelIstTimeHeater)
                    .addComponent(jButtonHeater))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSetTimeCooler)
                    .addComponent(jLabelIstTimeCooler)
                    .addComponent(jButtonCooler, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(385, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusAnzeigeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeAnzeigeHauptMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jTextFieldAnzeige)
                    .addComponent(statusAnzeigeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeAnzeigeHauptMenu)
                    .addComponent(startButton)
                    .addComponent(stopButton))
                .addGap(3, 3, 3)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusAnzeigeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusAnzeigeRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusAnzeigeRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCircLeft;
    private javax.swing.JButton jButtonCircRight;
    private javax.swing.JButton jButtonCooler;
    private javax.swing.JButton jButtonDamper;
    private javax.swing.JButton jButtonEthylen;
    private javax.swing.JButton jButtonFreshAir;
    private javax.swing.JButton jButtonHeater;
    private javax.swing.JButton jButtonSuction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCo2Soll;
    private javax.swing.JLabel jLabelCo2Tol;
    private javax.swing.JLabel jLabelDampSoll;
    private javax.swing.JLabel jLabelDampTol;
    private javax.swing.JLabel jLabelEthylSoll;
    private javax.swing.JLabel jLabelEthylTol;
    private javax.swing.JLabel jLabelIstTimeCircLeft;
    private javax.swing.JLabel jLabelIstTimeCooler;
    private javax.swing.JLabel jLabelIstTimeDamper;
    private javax.swing.JLabel jLabelIstTimeEthylen;
    private javax.swing.JLabel jLabelIstTimeFreshAir;
    private javax.swing.JLabel jLabelIstTimeHeater;
    private javax.swing.JLabel jLabelIstTimeRight;
    private javax.swing.JLabel jLabelIstTimeSuction;
    private javax.swing.JLabel jLabelManuel1;
    private javax.swing.JLabel jLabelManuel2;
    private javax.swing.JLabel jLabelManuel3;
    private javax.swing.JLabel jLabelManuel4;
    private javax.swing.JLabel jLabelMultiCo2;
    private javax.swing.JLabel jLabelMultiDamp;
    private javax.swing.JLabel jLabelMultiEthyl;
    private javax.swing.JLabel jLabelMultiTemp;
    private javax.swing.JLabel jLabelSetTimeCircLeft;
    private javax.swing.JLabel jLabelSetTimeCircRight;
    private javax.swing.JLabel jLabelSetTimeCooler;
    private javax.swing.JLabel jLabelSetTimeDamper;
    private javax.swing.JLabel jLabelSetTimeEthylen;
    private javax.swing.JLabel jLabelSetTimeFreshAir;
    private javax.swing.JLabel jLabelSetTimeHeater;
    private javax.swing.JLabel jLabelSetTimeSuction;
    private javax.swing.JLabel jLabelTempSoll;
    private javax.swing.JLabel jLabelTempTol;
    private javax.swing.JLabel jLabelZ1In;
    private javax.swing.JLabel jLabelZ1Out;
    private javax.swing.JLabel jLabelZ2In;
    private javax.swing.JLabel jLabelZ2Out;
    private volatile javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaClientSeite;
    private javax.swing.JTextField jTextFieldAnzeige;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField statusAnzeigeRoom;
    private javax.swing.JButton stopButton;
    private javax.swing.JTextField timeAnzeigeHauptMenu;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jButtonCircLeft
     */
    public javax.swing.JButton getjButtonCircLeft() {
        return jButtonCircLeft;
    }

    /**
     * @param jButtonCircLeft the jButtonCircLeft to set
     */
    public void setjButtonCircLeft(javax.swing.JButton jButtonCircLeft) {
        this.jButtonCircLeft = jButtonCircLeft;
    }

    /**
     * @return the jButtonCircRight
     */
    public javax.swing.JButton getjButtonCircRight() {
        return jButtonCircRight;
    }

    /**
     * @param jButtonCircRight the jButtonCircRight to set
     */
    public void setjButtonCircRight(javax.swing.JButton jButtonCircRight) {
        this.jButtonCircRight = jButtonCircRight;
    }

    /**
     * @return the jButtonCooler
     */
    public javax.swing.JButton getjButtonCooler() {
        return jButtonCooler;
    }

    /**
     * @param jButtonCooler the jButtonCooler to set
     */
    public void setjButtonCooler(javax.swing.JButton jButtonCooler) {
        this.jButtonCooler = jButtonCooler;
    }

    /**
     * @return the jButtonDamper
     */
    public javax.swing.JButton getjButtonDamper() {
        return jButtonDamper;
    }

    /**
     * @param jButtonDamper the jButtonDamper to set
     */
    public void setjButtonDamper(javax.swing.JButton jButtonDamper) {
        this.jButtonDamper = jButtonDamper;
    }

    /**
     * @return the jButtonEthylen
     */
    public javax.swing.JButton getjButtonEthylen() {
        return jButtonEthylen;
    }

    /**
     * @param jButtonEthylen the jButtonEthylen to set
     */
    public void setjButtonEthylen(javax.swing.JButton jButtonEthylen) {
        this.jButtonEthylen = jButtonEthylen;
    }

    /**
     * @return the jButtonFreshAir
     */
    public javax.swing.JButton getjButtonFreshAir() {
        return jButtonFreshAir;
    }

    /**
     * @param jButtonFreshAir the jButtonFreshAir to set
     */
    public void setjButtonFreshAir(javax.swing.JButton jButtonFreshAir) {
        this.jButtonFreshAir = jButtonFreshAir;
    }

    /**
     * @return the jButtonHeater
     */
    public javax.swing.JButton getjButtonHeater() {
        return jButtonHeater;
    }

    /**
     * @param jButtonHeater the jButtonHeater to set
     */
    public void setjButtonHeater(javax.swing.JButton jButtonHeater) {
        this.jButtonHeater = jButtonHeater;
    }

    /**
     * @return the jButtonSuction
     */
    public javax.swing.JButton getjButtonSuction() {
        return jButtonSuction;
    }

    /**
     * @param jButtonSuction the jButtonSuction to set
     */
    public void setjButtonSuction(javax.swing.JButton jButtonSuction) {
        this.jButtonSuction = jButtonSuction;
    }




    /**
     * @return the jLabelCo2Soll
     */
    public javax.swing.JLabel getjLabelCo2Soll() {
        return jLabelCo2Soll;
    }

    /**  
     * @param jLabelCo2Soll the jLabelCo2Soll to set
     */
    public void setjLabelCo2Soll(javax.swing.JLabel jLabelCo2Soll) {
        this.jLabelCo2Soll = jLabelCo2Soll;
    }

    /**
     * @return the jLabelCo2Tol
     */
    public javax.swing.JLabel getjLabelCo2Tol() {
        return jLabelCo2Tol;
    }

    /**
     * @param jLabelCo2Tol the jLabelCo2Tol to set
     */
    public void setjLabelCo2Tol(javax.swing.JLabel jLabelCo2Tol) {
        this.jLabelCo2Tol = jLabelCo2Tol;
    }

    /**
     * @return the jLabelDampSoll
     */
    public javax.swing.JLabel getjLabelDampSoll() {
        return jLabelDampSoll;
    }

    /**
     * @param jLabelDampSoll the jLabelDampSoll to set
     */
    public void setjLabelDampSoll(javax.swing.JLabel jLabelDampSoll) {
        this.jLabelDampSoll = jLabelDampSoll;
    }

    /**
     * @return the jLabelDampTol
     */
    public javax.swing.JLabel getjLabelDampTol() {
        return jLabelDampTol;
    }

    /**
     * @param jLabelDampTol the jLabelDampTol to set
     */
    public void setjLabelDampTol(javax.swing.JLabel jLabelDampTol) {
        this.jLabelDampTol = jLabelDampTol;
    }

    /**
     * @return the jLabelEthylSoll
     */
    public javax.swing.JLabel getjLabelEthylSoll() {
        return jLabelEthylSoll;
    }

    /**
     * @param jLabelEthylSoll the jLabelEthylSoll to set
     */
    public void setjLabelEthylSoll(javax.swing.JLabel jLabelEthylSoll) {
        this.jLabelEthylSoll = jLabelEthylSoll;
    }

    /**
     * @return the jLabelEthylTol
     */
    public javax.swing.JLabel getjLabelEthylTol() {
        return jLabelEthylTol;
    }

    /**
     * @param jLabelEthylTol the jLabelEthylTol to set
     */
    public void setjLabelEthylTol(javax.swing.JLabel jLabelEthylTol) {
        this.jLabelEthylTol = jLabelEthylTol;
    }

    /**
     * @return the jLabelIstTimeCircLeft
     */
    public javax.swing.JLabel getjLabelIstTimeCircLeft() {
        return jLabelIstTimeCircLeft;
    }

    /**
     * @param jLabelIstTimeCircLeft the jLabelIstTimeCircLeft to set
     */
    public void setjLabelIstTimeCircLeft(javax.swing.JLabel jLabelIstTimeCircLeft) {
        this.jLabelIstTimeCircLeft = jLabelIstTimeCircLeft;
    }

    /**
     * @return the jLabelIstTimeCooler
     */
    public javax.swing.JLabel getjLabelIstTimeCooler() {
        return jLabelIstTimeCooler;
    }

    /**
     * @param jLabelIstTimeCooler the jLabelIstTimeCooler to set
     */
    public void setjLabelIstTimeCooler(javax.swing.JLabel jLabelIstTimeCooler) {
        this.jLabelIstTimeCooler = jLabelIstTimeCooler;
    }

    /**
     * @return the jLabelIstTimeDamper
     */
    public javax.swing.JLabel getjLabelIstTimeDamper() {
        return jLabelIstTimeDamper;
    }

    /**
     * @param jLabelIstTimeDamper the jLabelIstTimeDamper to set
     */
    public void setjLabelIstTimeDamper(javax.swing.JLabel jLabelIstTimeDamper) {
        this.jLabelIstTimeDamper = jLabelIstTimeDamper;
    }

    /**
     * @return the jLabelIstTimeEthylen
     */
    public javax.swing.JLabel getjLabelIstTimeEthylen() {
        return jLabelIstTimeEthylen;
    }

    /**
     * @param jLabelIstTimeEthylen the jLabelIstTimeEthylen to set
     */
    public void setjLabelIstTimeEthylen(javax.swing.JLabel jLabelIstTimeEthylen) {
        this.jLabelIstTimeEthylen = jLabelIstTimeEthylen;
    }

    /**
     * @return the jLabelIstTimeFreshAir
     */
    public javax.swing.JLabel getjLabelIstTimeFreshAir() {
        return jLabelIstTimeFreshAir;
    }

    /**
     * @param jLabelIstTimeFreshAir the jLabelIstTimeFreshAir to set
     */
    public void setjLabelIstTimeFreshAir(javax.swing.JLabel jLabelIstTimeFreshAir) {
        this.jLabelIstTimeFreshAir = jLabelIstTimeFreshAir;
    }

    /**
     * @return the jLabelIstTimeHeater
     */
    public javax.swing.JLabel getjLabelIstTimeHeater() {
        return jLabelIstTimeHeater;
    }

    /**
     * @param jLabelIstTimeHeater the jLabelIstTimeHeater to set
     */
    public void setjLabelIstTimeHeater(javax.swing.JLabel jLabelIstTimeHeater) {
        this.jLabelIstTimeHeater = jLabelIstTimeHeater;
    }

    /**
     * @return the jLabelIstTimeRight
     */
    public javax.swing.JLabel getjLabelIstTimeRight() {
        return jLabelIstTimeRight;
    }

    /**
     * @param jLabelIstTimeRight the jLabelIstTimeRight to set
     */
    public void setjLabelIstTimeRight(javax.swing.JLabel jLabelIstTimeRight) {
        this.jLabelIstTimeRight = jLabelIstTimeRight;
    }

    /**
     * @return the jLabelIstTimeSuction
     */
    public javax.swing.JLabel getjLabelIstTimeSuction() {
        return jLabelIstTimeSuction;
    }

    /**
     * @param jLabelIstTimeSuction the jLabelIstTimeSuction to set
     */
    public void setjLabelIstTimeSuction(javax.swing.JLabel jLabelIstTimeSuction) {
        this.jLabelIstTimeSuction = jLabelIstTimeSuction;
    }

    /**
     * @return the jLabelManuel1
     */
    public javax.swing.JLabel getjLabelManuel1() {
        return jLabelManuel1;
    }

    /**
     * @param jLabelManuel1 the jLabelManuel1 to set
     */
    public void setjLabelManuel1(javax.swing.JLabel jLabelManuel1) {
        this.jLabelManuel1 = jLabelManuel1;
    }

    /**
     * @return the jLabelManuel2
     */
    public javax.swing.JLabel getjLabelManuel2() {
        return jLabelManuel2;
    }

    /**
     * @param jLabelManuel2 the jLabelManuel2 to set
     */
    public void setjLabelManuel2(javax.swing.JLabel jLabelManuel2) {
        this.jLabelManuel2 = jLabelManuel2;
    }

    /**
     * @return the jLabelManuel3
     */
    public javax.swing.JLabel getjLabelManuel3() {
        return jLabelManuel3;
    }

    /**
     * @param jLabelManuel3 the jLabelManuel3 to set
     */
    public void setjLabelManuel3(javax.swing.JLabel jLabelManuel3) {
        this.jLabelManuel3 = jLabelManuel3;
    }

    /**
     * @return the jLabelManuel4
     */
    public javax.swing.JLabel getjLabelManuel4() {
        return jLabelManuel4;
    }

    /**
     * @param jLabelManuel4 the jLabelManuel4 to set
     */
    public void setjLabelManuel4(javax.swing.JLabel jLabelManuel4) {
        this.jLabelManuel4 = jLabelManuel4;
    }

    /**
     * @return the jLabelSetTimeCircLeft
     */
    public javax.swing.JLabel getjLabelSetTimeCircLeft() {
        return jLabelSetTimeCircLeft;
    }

    /**
     * @param jLabelSetTimeCircLeft the jLabelSetTimeCircLeft to set
     */
    public void setjLabelSetTimeCircLeft(javax.swing.JLabel jLabelSetTimeCircLeft) {
        this.jLabelSetTimeCircLeft = jLabelSetTimeCircLeft;
    }

    /**
     * @return the jLabelSetTimeCircRight
     */
    public javax.swing.JLabel getjLabelSetTimeCircRight() {
        return jLabelSetTimeCircRight;
    }

    /**
     * @param jLabelSetTimeCircRight the jLabelSetTimeCircRight to set
     */
    public void setjLabelSetTimeCircRight(javax.swing.JLabel jLabelSetTimeCircRight) {
        this.jLabelSetTimeCircRight = jLabelSetTimeCircRight;
    }

    /**
     * @return the jLabelSetTimeCooler
     */
    public javax.swing.JLabel getjLabelSetTimeCooler() {
        return jLabelSetTimeCooler;
    }

    /**
     * @param jLabelSetTimeCooler the jLabelSetTimeCooler to set
     */
    public void setjLabelSetTimeCooler(javax.swing.JLabel jLabelSetTimeCooler) {
        this.jLabelSetTimeCooler = jLabelSetTimeCooler;
    }

    /**
     * @return the jLabelSetTimeDamper
     */
    public javax.swing.JLabel getjLabelSetTimeDamper() {
        return jLabelSetTimeDamper;
    }

    /**
     * @param jLabelSetTimeDamper the jLabelSetTimeDamper to set
     */
    public void setjLabelSetTimeDamper(javax.swing.JLabel jLabelSetTimeDamper) {
        this.jLabelSetTimeDamper = jLabelSetTimeDamper;
    }

    /**
     * @return the jLabelSetTimeEthylen
     */
    public javax.swing.JLabel getjLabelSetTimeEthylen() {
        return jLabelSetTimeEthylen;
    }

    /**
     * @param jLabelSetTimeEthylen the jLabelSetTimeEthylen to set
     */
    public void setjLabelSetTimeEthylen(javax.swing.JLabel jLabelSetTimeEthylen) {
        this.jLabelSetTimeEthylen = jLabelSetTimeEthylen;
    }

    /**
     * @return the jLabelSetTimeFreshAir
     */
    public javax.swing.JLabel getjLabelSetTimeFreshAir() {
        return jLabelSetTimeFreshAir;
    }

    /**
     * @param jLabelSetTimeFreshAir the jLabelSetTimeFreshAir to set
     */
    public void setjLabelSetTimeFreshAir(javax.swing.JLabel jLabelSetTimeFreshAir) {
        this.jLabelSetTimeFreshAir = jLabelSetTimeFreshAir;
    }

    /**
     * @return the jLabelSetTimeHeater
     */
    public javax.swing.JLabel getjLabelSetTimeHeater() {
        return jLabelSetTimeHeater;
    }

    /**
     * @param jLabelSetTimeHeater the jLabelSetTimeHeater to set
     */
    public void setjLabelSetTimeHeater(javax.swing.JLabel jLabelSetTimeHeater) {
        this.jLabelSetTimeHeater = jLabelSetTimeHeater;
    }

    /**
     * @return the jLabelSetTimeSuction
     */
    public javax.swing.JLabel getjLabelSetTimeSuction() {
        return jLabelSetTimeSuction;
    }

    /**
     * @param jLabelSetTimeSuction the jLabelSetTimeSuction to set
     */
    public void setjLabelSetTimeSuction(javax.swing.JLabel jLabelSetTimeSuction) {
        this.jLabelSetTimeSuction = jLabelSetTimeSuction;
    }

    /**
     * @return the jLabelTempSoll
     */
    public javax.swing.JLabel getjLabelTempSoll() {
        return jLabelTempSoll;
    }

    /**
     * @param jLabelTempSoll the jLabelTempSoll to set
     */
    public void setjLabelTempSoll(javax.swing.JLabel jLabelTempSoll) {
        this.jLabelTempSoll = jLabelTempSoll;
    }

    /**
     * @return the jLabelTempTol
     */
    public javax.swing.JLabel getjLabelTempTol() {
        return jLabelTempTol;
    }

    /**
     * @param jLabelTempTol the jLabelTempTol to set
     */
    public void setjLabelTempTol(javax.swing.JLabel jLabelTempTol) {
        this.jLabelTempTol = jLabelTempTol;
    }

    /**
     * @return the jLabelZ1In
     */
    public javax.swing.JLabel getjLabelZ1In() {
        return jLabelZ1In;
    }

    /**
     * @param jLabelZ1In the jLabelZ1In to set
     */
    public void setjLabelZ1In(javax.swing.JLabel jLabelZ1In) {
        this.jLabelZ1In = jLabelZ1In;
    }

    /**
     * @return the jLabelZ1Out
     */
    public javax.swing.JLabel getjLabelZ1Out() {
        return jLabelZ1Out;
    }

    /**
     * @param jLabelZ1Out the jLabelZ1Out to set
     */
    public void setjLabelZ1Out(javax.swing.JLabel jLabelZ1Out) {
        this.jLabelZ1Out = jLabelZ1Out;
    }

    /**
     * @return the jLabelZ2In
     */
    public javax.swing.JLabel getjLabelZ2In() {
        return jLabelZ2In;
    }

    /**
     * @param jLabelZ2In the jLabelZ2In to set
     */
    public void setjLabelZ2In(javax.swing.JLabel jLabelZ2In) {
        this.jLabelZ2In = jLabelZ2In;
    }

    /**
     * @return the jLabelZ2Out
     */
    public javax.swing.JLabel getjLabelZ2Out() {
        return jLabelZ2Out;
    }

    /**
     * @param jLabelZ2Out the jLabelZ2Out to set
     */
    public void setjLabelZ2Out(javax.swing.JLabel jLabelZ2Out) {
        this.jLabelZ2Out = jLabelZ2Out;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel10
     */
    public javax.swing.JPanel getjPanel10() {
        return jPanel10;
    }

    /**
     * @param jPanel10 the jPanel10 to set
     */
    public void setjPanel10(javax.swing.JPanel jPanel10) {
        this.jPanel10 = jPanel10;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() { 
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @param jPanel4 the jPanel4 to set
     */
    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @param jPanel5 the jPanel5 to set
     */
    public void setjPanel5(javax.swing.JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    /**
     * @return the jPanel6
     */
    public javax.swing.JPanel getjPanel6() {
        return jPanel6;
    }

    /**
     * @param jPanel6 the jPanel6 to set
     */
    public void setjPanel6(javax.swing.JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jTextAreaClientSeite
     */
    public javax.swing.JTextArea getjTextAreaClientSeite() {
        return jTextAreaClientSeite;
    }

    /**
     * @param jTextAreaClientSeite the jTextAreaClientSeite to set
     */
    public void setjTextAreaClientSeite(javax.swing.JTextArea jTextAreaClientSeite) {
        this.jTextAreaClientSeite = jTextAreaClientSeite;
    }

    /**
     * @return the jTextFieldAnzeige
     */
    public javax.swing.JTextField getjTextFieldAnzeige() {
        return jTextFieldAnzeige;
    }
 
    /** 
     * @param jTextFieldAnzeige the jTextFieldAnzeige to set
     */
    public void setjTextFieldAnzeige(javax.swing.JTextField jTextFieldAnzeige) {
        this.jTextFieldAnzeige = jTextFieldAnzeige;
    } 

 
    /**
     * @return the startButton
     */
    public javax.swing.JButton getStartButton() {
        return startButton;
    }

    /**
     * @param startButton the startButton to set
     */
    public void setStartButton(javax.swing.JButton startButton) {
        this.startButton = startButton;
    }

    /**
     * @return the statusAnzeigeRoom
     */
    public javax.swing.JTextField getStatusAnzeigeRoom() {
        return statusAnzeigeRoom;
    }

    /**
     * @param statusAnzeigeRoom the statusAnzeigeRoom to set
     */
    public void setStatusAnzeigeRoom(javax.swing.JTextField statusAnzeigeRoom) {
        this.statusAnzeigeRoom = statusAnzeigeRoom;
    }

    /**
     * @return the stopButton
     */
    public javax.swing.JButton getStopButton() {
        return stopButton;
    }

    /**
     * @param stopButton the stopButton to set
     */
    public void setStopButton(javax.swing.JButton stopButton) {
        this.stopButton = stopButton;
    }

    /**
     * @return the timeAnzeigeHauptMenu
     */
    public javax.swing.JTextField getTimeAnzeigeHauptMenu() {
        return timeAnzeigeHauptMenu;
    }

    /**
     * @param timeAnzeigeHauptMenu the timeAnzeigeHauptMenu to set
     */
    public void setTimeAnzeigeHauptMenu(javax.swing.JTextField timeAnzeigeHauptMenu) {
        this.timeAnzeigeHauptMenu = timeAnzeigeHauptMenu;
    }

    /**
     * @return the jLabelMultiCo2
     */
    public javax.swing.JLabel getjLabelMultiCo2() {
        return jLabelMultiCo2;
    }

    /**
     * @param jLabelMultiCo2 the jLabelMultiCo2 to set
     */
    public void setjLabelMultiCo2(javax.swing.JLabel jLabelMultiCo2) {
        this.jLabelMultiCo2 = jLabelMultiCo2;
    }

    /**
     * @return the jLabelMultiDamp
     */
    public javax.swing.JLabel getjLabelMultiDamp() {
        return jLabelMultiDamp;
    }

    /**
     * @param jLabelMultiDamp the jLabelMultiDamp to set
     */
    public void setjLabelMultiDamp(javax.swing.JLabel jLabelMultiDamp) {
        this.jLabelMultiDamp = jLabelMultiDamp;
    }

    /**
     * @return the jLabelMultiEthyl
     */
    public javax.swing.JLabel getjLabelMultiEthyl() {
        return jLabelMultiEthyl;
    }

    /**
     * @param jLabelMultiEthyl the jLabelMultiEthyl to set
     */
    public void setjLabelMultiEthyl(javax.swing.JLabel jLabelMultiEthyl) {
        this.jLabelMultiEthyl = jLabelMultiEthyl;
    }

    /**
     * @return the jLabelMultiTemp
     */
    public javax.swing.JLabel getjLabelMultiTemp() {
        return jLabelMultiTemp;
    }

    /**
     * @param jLabelMultiTemp the jLabelMultiTemp to set
     */
    public void setjLabelMultiTemp(javax.swing.JLabel jLabelMultiTemp) {
        this.jLabelMultiTemp = jLabelMultiTemp;
    }

  
}
