/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClientSeiteNeu;

import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
     
/**
 *
 * @author alisi
 */
public class RoomDisplay extends javax.swing.JFrame {

    /**
     * @return the jTextArea3
     */
    public javax.swing.JTextArea getjTextArea3() {
        return jTextArea3;
    }

    /**
     * @param jTextArea3 the jTextArea3 to set
     */
    public void setjTextArea3(javax.swing.JTextArea jTextArea3) {
        this.jTextArea3 = jTextArea3;
    }


    /**
     * Creates new form RoomDisplay
     */
    public RoomDisplay() {
    
//              try {
//      javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
//          
//        } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(RoomDisplay.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(RoomDisplay.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            Logger.getLogger(RoomDisplay.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Logger.getLogger(RoomDisplay.class.getName()).log(Level.SEVERE, null, ex);
//        }
   

try {
		    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
		        if ("Nimbus".equals(info.getName())) {
		            UIManager.setLookAndFeel(info.getClassName());
                            System.out.println(info.getClassName());
		            break;
		        }
		    }
		} catch (Exception e) {
		    // If Nimbus is not available, you can set the GUI to another look and feel.
		}


                initComponents();
      //        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        manuel1 = new javax.swing.JTextField();
        manuel2 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        manuel3 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        manuel4 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        z1In = new javax.swing.JTextField();
        z1Out = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        z2In = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        z2Out = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        multiTemp = new javax.swing.JTextField();
        multiDamp = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        multiCo2 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        multiEthyl = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        circulatingLeftP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBarCircLeft = new javax.swing.JProgressBar();
        circulatingRightP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBarCircRight = new javax.swing.JProgressBar();
        jProgressBarSuction = new javax.swing.JProgressBar();
        suctionP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FreshairP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBarFreshAir = new javax.swing.JProgressBar();
        jProgressBarEthylen = new javax.swing.JProgressBar();
        ethylenP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        damperP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jProgressBarDamper = new javax.swing.JProgressBar();
        jProgressBarHeater = new javax.swing.JProgressBar();
        heaterP = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBarCooler = new javax.swing.JProgressBar();
        coolerP = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelSetTimeCircLeft = new javax.swing.JLabel();
        jLabelSetTimeCircRight = new javax.swing.JLabel();
        jLabelSetTimeSuction = new javax.swing.JLabel();
        jLabelSetTimeFreshAir = new javax.swing.JLabel();
        jLabelSetTimeEthyl = new javax.swing.JLabel();
        jLabelSetTimeDamper = new javax.swing.JLabel();
        jLabelSetTimeHeater = new javax.swing.JLabel();
        jLabelSetTimeCooler = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        timeAnzeigeHauptMenu = new javax.swing.JTextField();
        statusAnzeigeRoom = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setEnabled(false);
        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 380));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Zonen"));
        jPanel15.setDoubleBuffered(false);

        manuel1.setEditable(false);
        manuel1.setBackground(new java.awt.Color(255, 255, 255));
        manuel1.setColumns(5);
        manuel1.setText("0");
        manuel1.setRequestFocusEnabled(false);
        manuel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuel1ActionPerformed(evt);
            }
        });

        manuel2.setEditable(false);
        manuel2.setBackground(new java.awt.Color(255, 255, 255));
        manuel2.setColumns(5);
        manuel2.setText("0");
        manuel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuel2ActionPerformed(evt);
            }
        });

        jLabel49.setText("[°C]");

        jLabel52.setText("[°C]");

        jLabel33.setForeground(new java.awt.Color(51, 255, 51));
        jLabel33.setText("M1");

        jLabel39.setText("M2");

        jLabel40.setForeground(new java.awt.Color(51, 51, 255));
        jLabel40.setText("M3");

        manuel3.setEditable(false);
        manuel3.setBackground(new java.awt.Color(255, 255, 255));
        manuel3.setColumns(5);
        manuel3.setText("0");
        manuel3.setRequestFocusEnabled(false);
        manuel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuel3ActionPerformed(evt);
            }
        });

        jLabel53.setText("[°C]");

        jLabel41.setBackground(new java.awt.Color(153, 153, 153));
        jLabel41.setText("M4");

        manuel4.setEditable(false);
        manuel4.setBackground(new java.awt.Color(255, 255, 255));
        manuel4.setColumns(5);
        manuel4.setText("0");
        manuel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuel4ActionPerformed(evt);
            }
        });

        jLabel54.setText("[°C]");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(12, 12, 12)
                        .addComponent(manuel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(manuel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manuel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manuel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(manuel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel40)
                    .addComponent(manuel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(manuel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel41)
                    .addComponent(manuel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54))
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Zonen"));
        jPanel14.setDoubleBuffered(false);

        z1In.setEditable(false);
        z1In.setBackground(new java.awt.Color(255, 255, 255));
        z1In.setColumns(5);
        z1In.setText("0");
        z1In.setRequestFocusEnabled(false);
        z1In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z1InActionPerformed(evt);
            }
        });

        z1Out.setEditable(false);
        z1Out.setBackground(new java.awt.Color(255, 255, 255));
        z1Out.setColumns(5);
        z1Out.setText("0");
        z1Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z1OutActionPerformed(evt);
            }
        });

        jLabel48.setText("[°C]");

        jLabel51.setText("[°C]");

        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("In1");

        jLabel32.setText("Out1");

        jLabel27.setText("In2");

        z2In.setEditable(false);
        z2In.setBackground(new java.awt.Color(255, 255, 255));
        z2In.setColumns(5);
        z2In.setText("0");
        z2In.setRequestFocusEnabled(false);
        z2In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2InActionPerformed(evt);
            }
        });

        jLabel47.setText("[°C]");

        jLabel28.setText("Out2");

        z2Out.setEditable(false);
        z2Out.setBackground(new java.awt.Color(255, 255, 255));
        z2Out.setColumns(5);
        z2Out.setText("0");
        z2Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2OutActionPerformed(evt);
            }
        });

        jLabel50.setText("[°C]");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel29)
                        .addGap(12, 12, 12)
                        .addComponent(z1In, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel27))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(z1Out, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(z2In, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(z2Out, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel50)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(z1In, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(jLabel27)
                    .addComponent(z2In, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(z1Out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel28)
                    .addComponent(z2Out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Zonen"));
        jPanel16.setDoubleBuffered(false);

        jLabel55.setText("[°C]");

        jLabel30.setText("Temp.");

        jLabel22.setText("Damp.");

        multiTemp.setEditable(false);
        multiTemp.setBackground(new java.awt.Color(255, 102, 102));
        multiTemp.setColumns(5);
        multiTemp.setText("0");
        multiTemp.setPreferredSize(new java.awt.Dimension(55, 25));
        multiTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiTempActionPerformed(evt);
            }
        });

        multiDamp.setEditable(false);
        multiDamp.setBackground(new java.awt.Color(0, 255, 255));
        multiDamp.setColumns(5);
        multiDamp.setText("0");
        multiDamp.setPreferredSize(new java.awt.Dimension(55, 25));
        multiDamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiDampActionPerformed(evt);
            }
        });

        jLabel31.setText("Co2");

        multiCo2.setEditable(false);
        multiCo2.setBackground(new java.awt.Color(204, 204, 255));
        multiCo2.setColumns(5);
        multiCo2.setText("0");
        multiCo2.setPreferredSize(new java.awt.Dimension(55, 25));
        multiCo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiCo2ActionPerformed(evt);
            }
        });

        jLabel44.setText("ppm");

        jLabel36.setText("[%] ");

        jLabel23.setText("Ethyl.");

        multiEthyl.setEditable(false);
        multiEthyl.setBackground(new java.awt.Color(255, 255, 0));
        multiEthyl.setColumns(5);
        multiEthyl.setText("0");
        multiEthyl.setPreferredSize(new java.awt.Dimension(55, 25));
        multiEthyl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiEthylActionPerformed(evt);
            }
        });

        jLabel38.setText("ppm");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(7, 7, 7)
                        .addComponent(multiTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiDamp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiCo2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiEthyl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(jLabel38)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jLabel30)
                    .addComponent(multiTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(multiCo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(multiDamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel23)
                    .addComponent(multiEthyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setDoubleBuffered(false);

        startButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startButton.setText("Start"); // NOI18N

        stopButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stopButton.setText("Stop"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        circulatingLeftP.setBackground(new java.awt.Color(51, 255, 0));
        circulatingLeftP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        circulatingLeftP.setDoubleBuffered(false);

        jLabel1.setText("Circ.Left");

        javax.swing.GroupLayout circulatingLeftPLayout = new javax.swing.GroupLayout(circulatingLeftP);
        circulatingLeftP.setLayout(circulatingLeftPLayout);
        circulatingLeftPLayout.setHorizontalGroup(
            circulatingLeftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circulatingLeftPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        circulatingLeftPLayout.setVerticalGroup(
            circulatingLeftPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circulatingLeftPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jProgressBarCircLeft.setValue(20);
        jProgressBarCircLeft.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarCircLeft.setStringPainted(true);

        circulatingRightP.setBackground(new java.awt.Color(51, 255, 0));
        circulatingRightP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        circulatingRightP.setDoubleBuffered(false);

        jLabel2.setText("Circ.right");

        javax.swing.GroupLayout circulatingRightPLayout = new javax.swing.GroupLayout(circulatingRightP);
        circulatingRightP.setLayout(circulatingRightPLayout);
        circulatingRightPLayout.setHorizontalGroup(
            circulatingRightPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circulatingRightPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        circulatingRightPLayout.setVerticalGroup(
            circulatingRightPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circulatingRightPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jProgressBarCircRight.setValue(20);
        jProgressBarCircRight.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarCircRight.setStringPainted(true);

        jProgressBarSuction.setValue(20);
        jProgressBarSuction.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarSuction.setStringPainted(true);

        suctionP.setBackground(new java.awt.Color(51, 255, 0));
        suctionP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        suctionP.setDoubleBuffered(false);

        jLabel3.setText("Suction");

        javax.swing.GroupLayout suctionPLayout = new javax.swing.GroupLayout(suctionP);
        suctionP.setLayout(suctionPLayout);
        suctionPLayout.setHorizontalGroup(
            suctionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suctionPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        suctionPLayout.setVerticalGroup(
            suctionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suctionPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        FreshairP.setBackground(new java.awt.Color(51, 255, 0));
        FreshairP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        FreshairP.setDoubleBuffered(false);

        jLabel4.setText("FreshAir");

        javax.swing.GroupLayout FreshairPLayout = new javax.swing.GroupLayout(FreshairP);
        FreshairP.setLayout(FreshairPLayout);
        FreshairPLayout.setHorizontalGroup(
            FreshairPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FreshairPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FreshairPLayout.setVerticalGroup(
            FreshairPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FreshairPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jProgressBarFreshAir.setValue(20);
        jProgressBarFreshAir.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarFreshAir.setStringPainted(true);

        jProgressBarEthylen.setValue(20);
        jProgressBarEthylen.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarEthylen.setStringPainted(true);

        ethylenP.setBackground(new java.awt.Color(51, 255, 0));
        ethylenP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ethylenP.setDoubleBuffered(false);

        jLabel5.setText("Ethlylen");

        javax.swing.GroupLayout ethylenPLayout = new javax.swing.GroupLayout(ethylenP);
        ethylenP.setLayout(ethylenPLayout);
        ethylenPLayout.setHorizontalGroup(
            ethylenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ethylenPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ethylenPLayout.setVerticalGroup(
            ethylenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ethylenPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        damperP.setBackground(new java.awt.Color(51, 255, 0));
        damperP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        damperP.setDoubleBuffered(false);

        jLabel6.setText("Damper");

        javax.swing.GroupLayout damperPLayout = new javax.swing.GroupLayout(damperP);
        damperP.setLayout(damperPLayout);
        damperPLayout.setHorizontalGroup(
            damperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(damperPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        damperPLayout.setVerticalGroup(
            damperPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, damperPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jProgressBarDamper.setValue(20);
        jProgressBarDamper.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarDamper.setStringPainted(true);

        jProgressBarHeater.setValue(20);
        jProgressBarHeater.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarHeater.setStringPainted(true);

        heaterP.setBackground(new java.awt.Color(51, 255, 0));
        heaterP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        heaterP.setDoubleBuffered(false);

        jLabel7.setText("Heater");

        javax.swing.GroupLayout heaterPLayout = new javax.swing.GroupLayout(heaterP);
        heaterP.setLayout(heaterPLayout);
        heaterPLayout.setHorizontalGroup(
            heaterPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heaterPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        heaterPLayout.setVerticalGroup(
            heaterPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, heaterPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jProgressBarCooler.setValue(20);
        jProgressBarCooler.setPreferredSize(new java.awt.Dimension(145, 15));
        jProgressBarCooler.setStringPainted(true);

        coolerP.setBackground(new java.awt.Color(51, 255, 0));
        coolerP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        coolerP.setDoubleBuffered(false);

        jLabel8.setText("Cooler");

        javax.swing.GroupLayout coolerPLayout = new javax.swing.GroupLayout(coolerP);
        coolerP.setLayout(coolerPLayout);
        coolerPLayout.setHorizontalGroup(
            coolerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coolerPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coolerPLayout.setVerticalGroup(
            coolerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coolerPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jLabelSetTimeCircLeft.setText("jLabel9");

        jLabelSetTimeCircRight.setText("jLabel10");

        jLabelSetTimeSuction.setText("jLabel11");

        jLabelSetTimeFreshAir.setText("jLabel12");

        jLabelSetTimeEthyl.setText("jLabel13");

        jLabelSetTimeDamper.setText("jLabel14");

        jLabelSetTimeHeater.setText("jLabel15");

        jLabelSetTimeCooler.setText("jLabel16");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coolerP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heaterP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(damperP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ethylenP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FreshairP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suctionP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(circulatingRightP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(circulatingLeftP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSetTimeHeater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSetTimeDamper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSetTimeEthyl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSetTimeCooler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelSetTimeCircLeft)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelSetTimeFreshAir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSetTimeCircRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSetTimeSuction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBarCircRight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jProgressBarSuction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jProgressBarFreshAir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jProgressBarEthylen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jProgressBarDamper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jProgressBarHeater, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jProgressBarCooler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jProgressBarCircLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarCircLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeCircLeft))
                    .addComponent(circulatingLeftP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarCircRight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeCircRight))
                    .addComponent(circulatingRightP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarSuction, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeSuction))
                    .addComponent(suctionP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarFreshAir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeFreshAir))
                    .addComponent(FreshairP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarEthylen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeEthyl))
                    .addComponent(ethylenP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarDamper, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeDamper))
                    .addComponent(damperP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarHeater, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeHeater))
                    .addComponent(heaterP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProgressBarCooler, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSetTimeCooler))
                    .addComponent(coolerP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setDoubleBuffered(false);

        timeAnzeigeHauptMenu.setBackground(new java.awt.Color(0, 255, 255));
        timeAnzeigeHauptMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        timeAnzeigeHauptMenu.setText("Datum Uhrzeit"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeAnzeigeHauptMenu)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeAnzeigeHauptMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        statusAnzeigeRoom.setBackground(new java.awt.Color(0, 255, 255));
        statusAnzeigeRoom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statusAnzeigeRoom.setText("Status"); // NOI18N

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusAnzeigeRoom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(stopButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startButton))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnzeigeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopButton)
                    .addComponent(startButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportView(null);

        jTextArea1.setBackground(new java.awt.Color(0, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("CLIENT"));
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea2.setBackground(new java.awt.Color(0, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("SERVER"));
        jTextArea2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextArea2CaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multiTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiTempActionPerformed

    private void multiDampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiDampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiDampActionPerformed

    private void z2InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2InActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z2InActionPerformed

    private void z2OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2OutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z2OutActionPerformed

    private void multiCo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiCo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiCo2ActionPerformed

    private void multiEthylActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiEthylActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiEthylActionPerformed

    private void z1InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z1InActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z1InActionPerformed

    private void z1OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z1OutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z1OutActionPerformed

    private void manuel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manuel1ActionPerformed

    private void manuel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manuel2ActionPerformed

    private void manuel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manuel3ActionPerformed

    private void manuel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuel4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manuel4ActionPerformed

    private void jTextArea2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextArea2CaretUpdate
        // TODO add your handling code here:
        jTextArea2.getCaret().setDot(Integer.MAX_VALUE);//.setc
    }//GEN-LAST:event_jTextArea2CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FreshairP;
    private javax.swing.JPanel circulatingLeftP;
    private javax.swing.JPanel circulatingRightP;
    private javax.swing.JPanel coolerP;
    private javax.swing.JPanel damperP;
    private javax.swing.JPanel ethylenP;
    private javax.swing.JPanel heaterP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelSetTimeCircLeft;
    private javax.swing.JLabel jLabelSetTimeCircRight;
    private javax.swing.JLabel jLabelSetTimeCooler;
    private javax.swing.JLabel jLabelSetTimeDamper;
    private javax.swing.JLabel jLabelSetTimeEthyl;
    private javax.swing.JLabel jLabelSetTimeFreshAir;
    private javax.swing.JLabel jLabelSetTimeHeater;
    private javax.swing.JLabel jLabelSetTimeSuction;
    private volatile javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBarCircLeft;
    private javax.swing.JProgressBar jProgressBarCircRight;
    private javax.swing.JProgressBar jProgressBarCooler;
    private javax.swing.JProgressBar jProgressBarDamper;
    private javax.swing.JProgressBar jProgressBarEthylen;
    private javax.swing.JProgressBar jProgressBarFreshAir;
    private javax.swing.JProgressBar jProgressBarHeater;
    private javax.swing.JProgressBar jProgressBarSuction;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField manuel1;
    private javax.swing.JTextField manuel2;
    private javax.swing.JTextField manuel3;
    private javax.swing.JTextField manuel4;
    private javax.swing.JTextField multiCo2;
    private javax.swing.JTextField multiDamp;
    private javax.swing.JTextField multiEthyl;
    private javax.swing.JTextField multiTemp;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField statusAnzeigeRoom;
    private javax.swing.JButton stopButton;
    private javax.swing.JPanel suctionP;
    private javax.swing.JTextField timeAnzeigeHauptMenu;
    private javax.swing.JTextField z1In;
    private javax.swing.JTextField z1Out;
    private javax.swing.JTextField z2In;
    private javax.swing.JTextField z2Out;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the FreshairP
     */
    public javax.swing.JPanel getFreshairP() {
        return FreshairP;
    }

    /**
     * @param FreshairP the FreshairP to set
     */
    public void setFreshairP(javax.swing.JPanel FreshairP) {
        this.FreshairP = FreshairP;
    }

    /**
     * @return the circulatingLeftP
     */
    public javax.swing.JPanel getCirculatingLeftP() {
        return circulatingLeftP;
    }

    /**
     * @param circulatingLeftP the circulatingLeftP to set
     */
    public void setCirculatingLeftP(javax.swing.JPanel circulatingLeftP) {
        this.circulatingLeftP = circulatingLeftP;
    }

    /**
     * @return the circulatingRightP
     */
    public javax.swing.JPanel getCirculatingRightP() {
        return circulatingRightP;
    }

    /**
     * @param circulatingRightP the circulatingRightP to set
     */
    public void setCirculatingRightP(javax.swing.JPanel circulatingRightP) {
        this.circulatingRightP = circulatingRightP;
    }

    /**
     * @return the coolerP
     */
    public javax.swing.JPanel getCoolerP() {
        return coolerP;
    }

    /**
     * @param coolerP the coolerP to set
     */
    public void setCoolerP(javax.swing.JPanel coolerP) {
        this.coolerP = coolerP;
    }

    /**
     * @return the damperP
     */
    public javax.swing.JPanel getDamperP() {
        return damperP;
    }

    /**
     * @param damperP the damperP to set
     */
    public void setDamperP(javax.swing.JPanel damperP) {
        this.damperP = damperP;
    }

    /**
     * @return the ethylenP
     */
    public javax.swing.JPanel getEthylenP() {
        return ethylenP;
    }

    /**
     * @param ethylenP the ethylenP to set
     */
    public void setEthylenP(javax.swing.JPanel ethylenP) {
        this.ethylenP = ethylenP;
    }

    /**
     * @return the heaterP
     */
    public javax.swing.JPanel getHeaterP() {
        return heaterP;
    }

    /**
     * @param heaterP the heaterP to set
     */
    public void setHeaterP(javax.swing.JPanel heaterP) {
        this.heaterP = heaterP;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel22
     */
    public javax.swing.JLabel getjLabel22() {
        return jLabel22;
    }

    /**
     * @param jLabel22 the jLabel22 to set
     */
    public void setjLabel22(javax.swing.JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    /**
     * @return the jLabel23
     */
    public javax.swing.JLabel getjLabel23() {
        return jLabel23;
    }

    /**
     * @param jLabel23 the jLabel23 to set
     */
    public void setjLabel23(javax.swing.JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    /**
     * @return the jLabel27
     */
    public javax.swing.JLabel getjLabel27() {
        return jLabel27;
    }

    /**
     * @param jLabel27 the jLabel27 to set
     */
    public void setjLabel27(javax.swing.JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    /**
     * @return the jLabel28
     */
    public javax.swing.JLabel getjLabel28() {
        return jLabel28;
    }

    /**
     * @param jLabel28 the jLabel28 to set
     */
    public void setjLabel28(javax.swing.JLabel jLabel28) {
        this.jLabel28 = jLabel28;
    }

    /**
     * @return the jLabel29
     */
    public javax.swing.JLabel getjLabel29() {
        return jLabel29;
    }

    /**
     * @param jLabel29 the jLabel29 to set
     */
    public void setjLabel29(javax.swing.JLabel jLabel29) {
        this.jLabel29 = jLabel29;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel30
     */
    public javax.swing.JLabel getjLabel30() {
        return jLabel30;
    }

    /**
     * @param jLabel30 the jLabel30 to set
     */
    public void setjLabel30(javax.swing.JLabel jLabel30) {
        this.jLabel30 = jLabel30;
    }

    /**
     * @return the jLabel31
     */
    public javax.swing.JLabel getjLabel31() {
        return jLabel31;
    }

    /**
     * @param jLabel31 the jLabel31 to set
     */
    public void setjLabel31(javax.swing.JLabel jLabel31) {
        this.jLabel31 = jLabel31;
    }

    /**
     * @return the jLabel32
     */
    public javax.swing.JLabel getjLabel32() {
        return jLabel32;
    }

    /**
     * @param jLabel32 the jLabel32 to set
     */
    public void setjLabel32(javax.swing.JLabel jLabel32) {
        this.jLabel32 = jLabel32;
    }

    /**
     * @return the jLabel33
     */
    public javax.swing.JLabel getjLabel33() {
        return jLabel33;
    }

    /**
     * @param jLabel33 the jLabel33 to set
     */
    public void setjLabel33(javax.swing.JLabel jLabel33) {
        this.jLabel33 = jLabel33;
    }

    /**
     * @return the jLabel36
     */
    public javax.swing.JLabel getjLabel36() {
        return jLabel36;
    }

    /**
     * @param jLabel36 the jLabel36 to set
     */
    public void setjLabel36(javax.swing.JLabel jLabel36) {
        this.jLabel36 = jLabel36;
    }

    /**
     * @return the jLabel38
     */
    public javax.swing.JLabel getjLabel38() {
        return jLabel38;
    }

    /**
     * @param jLabel38 the jLabel38 to set
     */
    public void setjLabel38(javax.swing.JLabel jLabel38) {
        this.jLabel38 = jLabel38;
    }

    /**
     * @return the jLabel39
     */
    public javax.swing.JLabel getjLabel39() {
        return jLabel39;
    }

    /**
     * @param jLabel39 the jLabel39 to set
     */
    public void setjLabel39(javax.swing.JLabel jLabel39) {
        this.jLabel39 = jLabel39;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @return the jLabel40
     */
    public javax.swing.JLabel getjLabel40() {
        return jLabel40;
    }

    /**
     * @param jLabel40 the jLabel40 to set
     */
    public void setjLabel40(javax.swing.JLabel jLabel40) {
        this.jLabel40 = jLabel40;
    }

    /**
     * @return the jLabel41
     */
    public javax.swing.JLabel getjLabel41() {
        return jLabel41;
    }

    /**
     * @param jLabel41 the jLabel41 to set
     */
    public void setjLabel41(javax.swing.JLabel jLabel41) {
        this.jLabel41 = jLabel41;
    }

  

    /**
     * @return the jLabel44
     */
    public javax.swing.JLabel getjLabel44() {
        return jLabel44;
    }

    /**
     * @param jLabel44 the jLabel44 to set
     */
    public void setjLabel44(javax.swing.JLabel jLabel44) {
        this.jLabel44 = jLabel44;
    }

    /**
     * @return the jLabel47
     */
    public javax.swing.JLabel getjLabel47() {
        return jLabel47;
    }

    /**
     * @param jLabel47 the jLabel47 to set
     */
    public void setjLabel47(javax.swing.JLabel jLabel47) {
        this.jLabel47 = jLabel47;
    }

    /**
     * @return the jLabel48
     */
    public javax.swing.JLabel getjLabel48() {
        return jLabel48;
    }

    /**
     * @param jLabel48 the jLabel48 to set
     */
    public void setjLabel48(javax.swing.JLabel jLabel48) {
        this.jLabel48 = jLabel48;
    }

    /**
     * @return the jLabel49
     */
    public javax.swing.JLabel getjLabel49() {
        return jLabel49;
    }

    /**
     * @param jLabel49 the jLabel49 to set
     */
    public void setjLabel49(javax.swing.JLabel jLabel49) {
        this.jLabel49 = jLabel49;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    /**
     * @return the jLabel50
     */
    public javax.swing.JLabel getjLabel50() {
        return jLabel50;
    }

    /**
     * @param jLabel50 the jLabel50 to set
     */
    public void setjLabel50(javax.swing.JLabel jLabel50) {
        this.jLabel50 = jLabel50;
    }

    /**
     * @return the jLabel51
     */
    public javax.swing.JLabel getjLabel51() {
        return jLabel51;
    }

    /**
     * @param jLabel51 the jLabel51 to set
     */
    public void setjLabel51(javax.swing.JLabel jLabel51) {
        this.jLabel51 = jLabel51;
    }

    /**
     * @return the jLabel52
     */
    public javax.swing.JLabel getjLabel52() {
        return jLabel52;
    }

    /**
     * @param jLabel52 the jLabel52 to set
     */
    public void setjLabel52(javax.swing.JLabel jLabel52) {
        this.jLabel52 = jLabel52;
    }

    /**
     * @return the jLabel53
     */
    public javax.swing.JLabel getjLabel53() {
        return jLabel53;
    }

    /**
     * @param jLabel53 the jLabel53 to set
     */
    public void setjLabel53(javax.swing.JLabel jLabel53) {
        this.jLabel53 = jLabel53;
    }

    /**
     * @return the jLabel54
     */
    public javax.swing.JLabel getjLabel54() {
        return jLabel54;
    }

    /**
     * @param jLabel54 the jLabel54 to set
     */
    public void setjLabel54(javax.swing.JLabel jLabel54) {
        this.jLabel54 = jLabel54;
    }

    /**
     * @return the jLabel6
     */
    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    /**
     * @param jLabel6 the jLabel6 to set
     */
    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @param jLabel7 the jLabel7 to set
     */
    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @return the jLabel8
     */
    public javax.swing.JLabel getjLabel8() {
        return jLabel8;
    }

    /**
     * @param jLabel8 the jLabel8 to set
     */
    public void setjLabel8(javax.swing.JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    /**
     * @return the jLabelSetTimeCircLeft
     */
    public javax.swing.JLabel getjLabelSetTimeCircLeft() {
        return jLabelSetTimeCircLeft;
    }

    /**
     * @param jLabelSetTimeCircLeft the jLabelSetTimeCircLeft to set
     */
    public void setjLabelSetTimeCircLeft(javax.swing.JLabel jLabelSetTimeCircLeft) {
        this.jLabelSetTimeCircLeft = jLabelSetTimeCircLeft;
    }

    /**
     * @return the jLabelSetTimeCircRight
     */
    public javax.swing.JLabel getjLabelSetTimeCircRight() {
        return jLabelSetTimeCircRight;
    }

    /**
     * @param jLabelSetTimeCircRight the jLabelSetTimeCircRight to set
     */
    public void setjLabelSetTimeCircRight(javax.swing.JLabel jLabelSetTimeCircRight) {
        this.jLabelSetTimeCircRight = jLabelSetTimeCircRight;
    }

    /**
     * @return the jLabelSetTimeCooler
     */
    public javax.swing.JLabel getjLabelSetTimeCooler() {
        return jLabelSetTimeCooler;
    }

    /**
     * @param jLabelSetTimeCooler the jLabelSetTimeCooler to set
     */
    public void setjLabelSetTimeCooler(javax.swing.JLabel jLabelSetTimeCooler) {
        this.jLabelSetTimeCooler = jLabelSetTimeCooler;
    }

    /**
     * @return the jLabelSetTimeDamper
     */
    public javax.swing.JLabel getjLabelSetTimeDamper() {
        return jLabelSetTimeDamper;
    }

    /**
     * @param jLabelSetTimeDamper the jLabelSetTimeDamper to set
     */
    public void setjLabelSetTimeDamper(javax.swing.JLabel jLabelSetTimeDamper) {
        this.jLabelSetTimeDamper = jLabelSetTimeDamper;
    }

    /**
     * @return the jLabelSetTimeEthyl
     */
    public javax.swing.JLabel getjLabelSetTimeEthyl() {
        return jLabelSetTimeEthyl;
    }

    /**
     * @param jLabelSetTimeEthyl the jLabelSetTimeEthyl to set
     */
    public void setjLabelSetTimeEthyl(javax.swing.JLabel jLabelSetTimeEthyl) {
        this.jLabelSetTimeEthyl = jLabelSetTimeEthyl;
    }

    /**
     * @return the jLabelSetTimeFreshAir
     */
    public javax.swing.JLabel getjLabelSetTimeFreshAir() {
        return jLabelSetTimeFreshAir;
    }

    /**
     * @param jLabelSetTimeFreshAir the jLabelSetTimeFreshAir to set
     */
    public void setjLabelSetTimeFreshAir(javax.swing.JLabel jLabelSetTimeFreshAir) {
        this.jLabelSetTimeFreshAir = jLabelSetTimeFreshAir;
    }

    /**
     * @return the jLabelSetTimeHeater
     */
    public javax.swing.JLabel getjLabelSetTimeHeater() {
        return jLabelSetTimeHeater;
    }

    /**
     * @param jLabelSetTimeHeater the jLabelSetTimeHeater to set
     */
    public void setjLabelSetTimeHeater(javax.swing.JLabel jLabelSetTimeHeater) {
        this.jLabelSetTimeHeater = jLabelSetTimeHeater;
    }

    /**
     * @return the jLabelSetTimeSuction
     */
    public javax.swing.JLabel getjLabelSetTimeSuction() {
        return jLabelSetTimeSuction;
    }

    /**
     * @param jLabelSetTimeSuction the jLabelSetTimeSuction to set
     */
    public void setjLabelSetTimeSuction(javax.swing.JLabel jLabelSetTimeSuction) {
        this.jLabelSetTimeSuction = jLabelSetTimeSuction;
    }

    /** 
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public  void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel10
     */
    public javax.swing.JPanel getjPanel10() {
        return jPanel10;
    }

    /**
     * @param jPanel10 the jPanel10 to set
     */
    public void setjPanel10(javax.swing.JPanel jPanel10) {
        this.jPanel10 = jPanel10;
    }

   

    /**
     * @return the jPanel14
     */
    public javax.swing.JPanel getjPanel14() {
        return jPanel14;
    }

    /**
     * @param jPanel14 the jPanel14 to set
     */
    public void setjPanel14(javax.swing.JPanel jPanel14) {
        this.jPanel14 = jPanel14;
    }

    /**
     * @return the jPanel15
     */
    public javax.swing.JPanel getjPanel15() {
        return jPanel15;
    }

    /**
     * @param jPanel15 the jPanel15 to set
     */
    public void setjPanel15(javax.swing.JPanel jPanel15) {
        this.jPanel15 = jPanel15;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @param jPanel4 the jPanel4 to set
     */
    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @param jPanel5 the jPanel5 to set
     */
    public void setjPanel5(javax.swing.JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    /**
     * @return the jProgressBarCircLeft
     */
    public javax.swing.JProgressBar getjProgressBarCircLeft() {
        return jProgressBarCircLeft;
    }

    /**
     * @param jProgressBarCircLeft the jProgressBarCircLeft to set
     */
    public void setjProgressBarCircLeft(javax.swing.JProgressBar jProgressBarCircLeft) {
        this.jProgressBarCircLeft = jProgressBarCircLeft;
    }

    /**
     * @return the jProgressBarCircRight
     */
    public javax.swing.JProgressBar getjProgressBarCircRight() {
        return jProgressBarCircRight;
    }

    /**
     * @param jProgressBarCircRight the jProgressBarCircRight to set
     */
    public void setjProgressBarCircRight(javax.swing.JProgressBar jProgressBarCircRight) {
        this.jProgressBarCircRight = jProgressBarCircRight;
    }

    /**
     * @return the jProgressBarCooler
     */
    public javax.swing.JProgressBar getjProgressBarCooler() {
        return jProgressBarCooler;
    }

    /**
     * @param jProgressBarCooler the jProgressBarCooler to set
     */
    public void setjProgressBarCooler(javax.swing.JProgressBar jProgressBarCooler) {
        this.jProgressBarCooler = jProgressBarCooler;
    }

    /**
     * @return the jProgressBarDamper
     */
    public javax.swing.JProgressBar getjProgressBarDamper() {
        return jProgressBarDamper;
    }

    /**
     * @param jProgressBarDamper the jProgressBarDamper to set
     */
    public void setjProgressBarDamper(javax.swing.JProgressBar jProgressBarDamper) {
        this.jProgressBarDamper = jProgressBarDamper;
    }

    /**
     * @return the jProgressBarEthylen
     */
    public javax.swing.JProgressBar getjProgressBarEthylen() {
        return jProgressBarEthylen;
    }

    /**
     * @param jProgressBarEthylen the jProgressBarEthylen to set
     */
    public void setjProgressBarEthylen(javax.swing.JProgressBar jProgressBarEthylen) {
        this.jProgressBarEthylen = jProgressBarEthylen;
    }

    /**
     * @return the jProgressBarFreshAir
     */
    public javax.swing.JProgressBar getjProgressBarFreshAir() {
        return jProgressBarFreshAir;
    }

    /**
     * @param jProgressBarFreshAir the jProgressBarFreshAir to set
     */
    public void setjProgressBarFreshAir(javax.swing.JProgressBar jProgressBarFreshAir) {
        this.jProgressBarFreshAir = jProgressBarFreshAir;
    }

    /**
     * @return the jProgressBarHeater
     */
    public javax.swing.JProgressBar getjProgressBarHeater() {
        return jProgressBarHeater;
    }

    /**
     * @param jProgressBarHeater the jProgressBarHeater to set
     */
    public void setjProgressBarHeater(javax.swing.JProgressBar jProgressBarHeater) {
        this.jProgressBarHeater = jProgressBarHeater;
    }

    /**
     * @return the jProgressBarSuction
     */
    public javax.swing.JProgressBar getjProgressBarSuction() {
        return jProgressBarSuction;
    }

    /**
     * @param jProgressBarSuction the jProgressBarSuction to set
     */
    public void setjProgressBarSuction(javax.swing.JProgressBar jProgressBarSuction) {
        this.jProgressBarSuction = jProgressBarSuction;
    }

    /**
     * @return the manuel1
     */
    public javax.swing.JTextField getManuel1() {
        return manuel1;
    }

    /**
     * @param manuel1 the manuel1 to set
     */
    public void setManuel1(javax.swing.JTextField manuel1) {
        this.manuel1 = manuel1;
    }

    /**
     * @return the manuel2
     */
    public javax.swing.JTextField getManuel2() {
        return manuel2;
    }

    /**
     * @return the jTextArea2
     */
    public javax.swing.JTextArea getjTextArea2() {
        return jTextArea2;
    }

    /**
     * @param jTextArea2 the jTextArea2 to set
     */
    public void setjTextArea2(javax.swing.JTextArea jTextArea2) {
        this.jTextArea2 = jTextArea2;
    }

    /**
     * @param manuel2 the manuel2 to set
     */
    public void setManuel2(javax.swing.JTextField manuel2) {
        this.manuel2 = manuel2;
    }

    /**
     * @return the manuel3
     */
    public javax.swing.JTextField getManuel3() {
        return manuel3;
    }

    /**
     * @param manuel3 the manuel3 to set
     */
    public void setManuel3(javax.swing.JTextField manuel3) {
        this.manuel3 = manuel3;
    }

    /**
     * @return the manuel4
     */
    public javax.swing.JTextField getManuel4() {
        return manuel4;
    }

    /**
     * @param manuel4 the manuel4 to set
     */
    public void setManuel4(javax.swing.JTextField manuel4) {
        this.manuel4 = manuel4;
    }

    /**
     * @return the multiCo2
     */
    public javax.swing.JTextField getMultiCo2() {
        return multiCo2;
    }

    /**
     * @param multiCo2 the multiCo2 to set
     */
    public void setMultiCo2(javax.swing.JTextField multiCo2) {
        this.multiCo2 = multiCo2;
    }

    /**
     * @return the multiDamp
     */
    public javax.swing.JTextField getMultiDamp() {
        return multiDamp;
    }

    /**
     * @param multiDamp the multiDamp to set
     */
    public void setMultiDamp(javax.swing.JTextField multiDamp) {
        this.multiDamp = multiDamp;
    }

    /**
     * @return the multiEthyl
     */
    public javax.swing.JTextField getMultiEthyl() {
        return multiEthyl;
    }

    /**
     * @param multiEthyl the multiEthyl to set
     */
    public void setMultiEthyl(javax.swing.JTextField multiEthyl) {
        this.multiEthyl = multiEthyl;
    }

    /**
     * @return the multiTemp
     */
    public javax.swing.JTextField getMultiTemp() {
        return multiTemp;
    }

    /**
     * @param multiTemp the multiTemp to set
     */
    public void setMultiTemp(javax.swing.JTextField multiTemp) {
        this.multiTemp = multiTemp;
    }

    /**
     * @return the startButton
     */
    public javax.swing.JButton getStartButton() {
        return startButton;
    }

    /**
     * @param startButton the startButton to set
     */
    public void setStartButton(javax.swing.JButton startButton) {
        this.startButton = startButton;
    }

    /**
     * @return the statusAnzeigeRoom
     */
    public javax.swing.JTextField getStatusAnzeigeRoom() {
        return statusAnzeigeRoom;
    }

    /**
     * @param statusAnzeigeRoom the statusAnzeigeRoom to set
     */
    public void setStatusAnzeigeRoom(javax.swing.JTextField statusAnzeigeRoom) {
        this.statusAnzeigeRoom = statusAnzeigeRoom;
    }

    /**
     * @return the stopButton
     */
    public javax.swing.JButton getStopButton() {
        return stopButton;
    }

    /**
     * @param stopButton the stopButton to set
     */
    public void setStopButton(javax.swing.JButton stopButton) {
        this.stopButton = stopButton;
    }

    /**
     * @return the suctionP
     */
    public javax.swing.JPanel getSuctionP() {
        return suctionP;
    }

    /**
     * @param suctionP the suctionP to set
     */
    public void setSuctionP(javax.swing.JPanel suctionP) {
        this.suctionP = suctionP;
    }

    /**
     * @return the timeAnzeigeHauptMenu
     */
    public javax.swing.JTextField getTimeAnzeigeHauptMenu() {
        return timeAnzeigeHauptMenu;
    }

    /**
     * @param timeAnzeigeHauptMenu the timeAnzeigeHauptMenu to set
     */
    public void setTimeAnzeigeHauptMenu(javax.swing.JTextField timeAnzeigeHauptMenu) {
        this.timeAnzeigeHauptMenu = timeAnzeigeHauptMenu;
    }

    /**
     * @return the z1In
     */
    public javax.swing.JTextField getZ1In() {
        return z1In;
    }

    /**
     * @param z1In the z1In to set
     */
    public void setZ1In(javax.swing.JTextField z1In) {
        this.z1In = z1In;
    }

    /**
     * @return the z1Out
     */
    public javax.swing.JTextField getZ1Out() {
        return z1Out;
    }

    /**
     * @param z1Out the z1Out to set
     */
    public void setZ1Out(javax.swing.JTextField z1Out) {
        this.z1Out = z1Out;
    }

    /**
     * @return the z2In
     */
    public javax.swing.JTextField getZ2In() {
        return z2In;
    }

    /**
     * @param z2In the z2In to set
     */
    public void setZ2In(javax.swing.JTextField z2In) {
        this.z2In = z2In;
    }

    /**
     * @return the z2Out
     */
    public javax.swing.JTextField getZ2Out() {
        return z2Out;
    }

    /**
     * @param z2Out the z2Out to set
     */
    public void setZ2Out(javax.swing.JTextField z2Out) {
        this.z2Out = z2Out;
    }

    /**
     * @return the jTextArea1
     */
    public javax.swing.JTextArea getjTextArea1() {
        return jTextArea1;
    }

    /**
     * @param jTextArea1 the jTextArea1 to set
     */
    public void setjTextArea1(javax.swing.JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

 

}
